SESSION_KEY = "tourops_presentation"

STAGES = (
    ("agent", "Agent"),
    ("accountant", "Accountant"),
    ("owner", "Owner"),
)

STORY = {
    "tour_name": "Istanbul Escape",
    "package_name": "Istanbul Escape",
    "dates_label": "15–20 Sep",
    "start": "2026-09-15",
    "end": "2026-09-20",
    "capacity": 30,
    "price": "1000.00",
    "hotel": "Bosphorus Hotel",
    "transport": "Istanbul Transport",
    "guide": "Istanbul Local Guide",
    "maya_first": "Maya",
    "maya_last": "Hassan",
    "maya_email": "maya.hassan@example.com",
    "maya_phone": "+90 532 441 2290",
    "maya_city": "Amman",
    "maya_country": "Jordan",
    "maya_passport": "N8124459",
    "maya_nationality": "Jordanian",
    "companion_first": "Omar",
    "companion_last": "Hassan",
    "companion_passport": "N8124460",
    "companion_nationality": "Jordanian",
    "hotel_confirm": "BOS-1509-22",
    "guide_confirm": "GLD-IST-SEP",
    "transport_confirm": "VAN-16-SEP",
    "partial_amount": "500.00",
    "full_amount": "1500.00",
    "deposit_ref": "ARB-DEP-1509",
    "balance_ref": "ARB-BAL-1509",
    "hotel_pay_ref": "GARANTI-WIRE-1509",
    "maya_notes": "Walk-in at the desk. Two seats on Istanbul Escape, 15–20 Sep.",
    "booking_notes": "Maya Hassan + Omar Hassan. Twin room preference.",
    "refund_reason": "Family emergency — Omar cannot travel on 15 September.",
    "pay_notes": "Deposit collected at the desk for Maya Hassan, Istanbul Escape.",
    "hotel_pay_notes": "30% on confirmation, per Bosphorus Hotel terms.",
}
