from django.urls import reverse


def test_key_api_routes_reverse():
    assert reverse("customers_api:collection") == "/api/customers/"
    assert reverse("customers_api:balance", args=["abc"]) == "/api/customers/abc/balance/"
    assert reverse("bookings_api:confirm", args=["abc"]) == "/api/bookings/abc/confirm/"
    assert reverse("bookings_api:complete", args=["abc"]) == "/api/bookings/abc/complete/"
    assert reverse("bookings_api:invoice", args=["abc"]) == "/api/bookings/abc/invoice/"
    assert reverse("tours_api:availability", args=["abc"]) == "/api/tours/abc/availability/"
    assert reverse("tours_api:expenses", args=["abc"]) == "/api/tours/abc/expenses/"
    assert reverse("tours_api:profitability", args=["abc"]) == "/api/tours/abc/profitability/"
    assert reverse("packages_api:tours", args=["abc"]) == "/api/packages/abc/tours/"
    assert reverse("suppliers_api:payments", args=["abc"]) == "/api/suppliers/abc/payments/"
    assert reverse("suppliers_api:balance", args=["abc"]) == "/api/suppliers/abc/balance/"
    assert reverse("invoices_api:payments", args=["abc"]) == "/api/invoices/abc/payments/"
    assert reverse("invoices_api:cancel", args=["abc"]) == "/api/invoices/abc/cancel/"
    assert reverse("payments_api:receipt", args=["abc"]) == "/api/payments/abc/receipt/"
    assert reverse("payments_api:void", args=["abc"]) == "/api/payments/abc/void/"
    assert reverse("receipts_api:collection") == "/api/receipts/"
    assert reverse("refunds_api:approve", args=["abc"]) == "/api/refunds/abc/approve/"
    assert reverse("supplier_payments_api:void", args=["abc"]) == "/api/supplier-payments/abc/void/"
    assert reverse("supplier_reservations_api:collection") == "/api/supplier-reservations/"
    assert reverse("supplier_reservations_api:confirm", args=["abc"]) == "/api/supplier-reservations/abc/confirm/"
    assert reverse("tours_api:reservations", args=["abc"]) == "/api/tours/abc/reservations/"
    assert reverse("tours_api:accommodation", args=["abc"]) == "/api/tours/abc/accommodation/"
    assert reverse("supplier_reservations:email", args=["abc"]) == "/supplier-reservations/abc/email/"
    assert reverse("finance_api:receivables") == "/api/finance/receivables/"
    assert reverse("finance_api:payables") == "/api/finance/payables/"
    assert reverse("finance_api:customer_balances") == "/api/finance/customer-balances/"
    assert reverse("finance_api:supplier_balances") == "/api/finance/supplier-balances/"
    assert reverse("reports_api:profit_loss") == "/api/reports/profit-loss/"
    assert reverse("dashboard_api:owner") == "/api/dashboard/owner/"
    assert reverse("dashboard_api:accountant") == "/api/dashboard/accountant/"
    assert reverse("accounts_api:login") == "/api/auth/login/"
    assert reverse("accounts_api:me") == "/api/auth/me/"
    assert reverse("accounts_api:password_reset") == "/api/auth/password/reset/"
    assert reverse("accounts_api:users") == "/api/users/"
    assert reverse("suppliers_api:collection") == "/api/suppliers/"
    assert reverse("suppliers_api:services") == "/api/suppliers/services/"
    assert reverse("suppliers:service_create", args=["abc"]) == "/suppliers/abc/services/new/"
    assert reverse("suppliers:services") == "/suppliers/services/"
    assert reverse("suppliers:service_new") == "/suppliers/services/new/"
    assert reverse("suppliers:service_status", args=["abc", "def"]) == "/suppliers/abc/services/def/status/"
    assert reverse("suppliers_api:offerings", args=["abc"]) == "/api/suppliers/abc/services/"
    assert reverse("packages_api:collection") == "/api/packages/"
    assert reverse("tours_api:collection") == "/api/tours/"
    assert reverse("accounts:password_reset") == "/password/reset/"
    assert reverse("notifications_api:collection") == "/api/notifications/"
    assert reverse("notifications_api:read_all") == "/api/notifications/read-all/"
    assert reverse("audit_api:collection") == "/api/audit/"
    assert reverse("attachments_api:collection") == "/api/attachments/"
    assert reverse("attachments:list") == "/attachments/"
    assert reverse("attachments:preview", args=["abc"]) == "/attachments/abc/preview/"
