from __future__ import annotations


def _by_id(rows: list[dict], key: str, value: str) -> dict:
    for row in rows:
        if str(row.get(key)).lower() == str(value).lower():
            return row
    return {}


CUSTOMERS = [
    {
        "id": "cus-1001",
        "number": "CUS-1001",
        "first": "Fatima",
        "last": "Ghazzawi",
        "name": "Fatima Ghazzawi",
        "initials": "FG",
        "email": "fatima.g@example.com",
        "phone": "+961 71 555 0101",
        "status": "ACTIVE",
        "city": "Beirut",
        "country": "Lebanon",
        "upcoming": "Cairo Discovery · 12 Sep",
        "balance": 420,
        "bookings": 4,
        "lifetime": 8640,
        "passport": "LR445821",
        "passport_expiry": "18 Mar 2028",
        "emergency": "Rami Ghazzawi · +961 3 220 118",
    },
    {
        "id": "cus-1002",
        "number": "CUS-1002",
        "first": "Sarah",
        "last": "Ahmad",
        "name": "Sarah Ahmad",
        "initials": "SA",
        "email": "sarah.ahmad@example.com",
        "phone": "+20 10 4421 8890",
        "status": "ACTIVE",
        "city": "Cairo",
        "country": "Egypt",
        "upcoming": "Istanbul Explorer · 15 Sep",
        "balance": 0,
        "bookings": 6,
        "lifetime": 12450,
        "passport": "A21988341",
        "passport_expiry": "02 Nov 2029",
        "emergency": "Nour Ahmad · +20 12 300 4411",
    },
    {
        "id": "cus-1003",
        "number": "CUS-1003",
        "first": "Omar",
        "last": "Khalil",
        "name": "Omar Khalil",
        "initials": "OK",
        "email": "omar.khalil@example.com",
        "phone": "+971 50 118 2204",
        "status": "ACTIVE",
        "city": "Dubai",
        "country": "UAE",
        "upcoming": None,
        "balance": 1180,
        "bookings": 2,
        "lifetime": 3900,
        "passport": "N7782109",
        "passport_expiry": "09 Jan 2027",
        "emergency": "Lina Khalil · +971 50 900 1122",
    },
    {
        "id": "cus-1004",
        "number": "CUS-1004",
        "first": "Ali",
        "last": "Mansour",
        "name": "Ali Mansour",
        "initials": "AM",
        "email": "ali.mansour@example.com",
        "phone": "+961 76 330 441",
        "status": "INACTIVE",
        "city": "Tripoli",
        "country": "Lebanon",
        "upcoming": None,
        "balance": 0,
        "bookings": 1,
        "lifetime": 650,
        "passport": "—",
        "passport_expiry": "—",
        "emergency": "—",
    },
]

TOURS = [
    {
        "id": "tour-1001",
        "code": "TOUR-1001",
        "package_id": "pkg-1003",
        "package": "Cairo Heritage",
        "name": "Cairo Discovery",
        "city": "Cairo",
        "country": "Egypt",
        "start": "12 Sep 2026",
        "end": "16 Sep 2026",
        "dates": "12–16 Sep 2026",
        "capacity": 25,
        "booked": 18,
        "available": 7,
        "pct": 72,
        "price": 650,
        "revenue": 18200,
        "costs": 11900,
        "profit": 6300,
        "margin": 34.6,
        "status": "AVAILABLE",
        "projected": 4300,
    },
    {
        "id": "tour-1002",
        "code": "TOUR-1002",
        "package_id": "pkg-1001",
        "package": "Istanbul Essentials",
        "name": "Istanbul Explorer",
        "city": "Istanbul",
        "country": "Turkey",
        "start": "15 Sep 2026",
        "end": "20 Sep 2026",
        "dates": "15–20 Sep 2026",
        "capacity": 20,
        "booked": 20,
        "available": 0,
        "pct": 100,
        "price": 890,
        "revenue": 17800,
        "costs": 14200,
        "profit": 3600,
        "margin": 20.2,
        "status": "FULLY_BOOKED",
        "projected": 3600,
    },
    {
        "id": "tour-1003",
        "code": "TOUR-1003",
        "package_id": "pkg-1001",
        "package": "Istanbul Essentials",
        "name": "Istanbul Essentials — Late Sep",
        "city": "Istanbul",
        "country": "Turkey",
        "start": "20 Sep 2026",
        "end": "25 Sep 2026",
        "dates": "20–25 Sep 2026",
        "capacity": 16,
        "booked": 5,
        "available": 11,
        "pct": 31,
        "price": 699,
        "revenue": 3495,
        "costs": 2100,
        "profit": 1395,
        "margin": 39.9,
        "status": "AVAILABLE",
        "projected": 1395,
    },
    {
        "id": "tour-1004",
        "code": "TOUR-1004",
        "package_id": "pkg-1002",
        "package": "Dubai Escape",
        "name": "Dubai Escape — Sep",
        "city": "Dubai",
        "country": "UAE",
        "start": "22 Sep 2026",
        "end": "26 Sep 2026",
        "dates": "22–26 Sep 2026",
        "capacity": 22,
        "booked": 11,
        "available": 11,
        "pct": 50,
        "price": 849,
        "revenue": 9339,
        "costs": 5200,
        "profit": 4139,
        "margin": 44.3,
        "status": "AVAILABLE",
        "projected": 4139,
    },
]

PACKAGES = [
    {
        "id": "pkg-1001",
        "code": "PKG-1001",
        "name": "Istanbul Essentials",
        "city": "Istanbul",
        "duration": "5 days / 4 nights",
        "price": 699,
        "includes": "Hotel + Transfers + Guided tour",
        "status": "ACTIVE",
        "excluded": "Flights, personal expenses",
        "services": [
            {"id": "svc-1004", "supplier_id": "sup-1004", "supplier": "Bosphorus Hotel", "name": "Accommodation", "kind": "ACCOMMODATION", "estimated_cost": 9000},
            {"id": "svc-1005", "supplier_id": "sup-1005", "supplier": "Istanbul Transport", "name": "Airport Transfer", "kind": "TRANSPORTATION", "estimated_cost": 1500},
            {"id": "svc-1006", "supplier_id": "sup-1005", "supplier": "Istanbul Transport", "name": "Full-Day Transportation", "kind": "TRANSPORTATION", "estimated_cost": 3000},
            {"id": "svc-1007", "supplier_id": "sup-1006", "supplier": "Istanbul Local Guide", "name": "City Tour", "kind": "GUIDE", "estimated_cost": 2000},
        ],
    },
    {
        "id": "pkg-1002",
        "code": "PKG-1002",
        "name": "Dubai Escape",
        "city": "Dubai",
        "duration": "4 days / 3 nights",
        "price": 849,
        "includes": "Hotel + Desert safari + Marina cruise",
        "status": "ACTIVE",
        "excluded": "Flights, visa",
        "services": [
            {"id": "svc-1002", "supplier_id": "sup-1002", "supplier": "Beirut Transport Co.", "name": "Airport arrivals and old-city coach", "kind": "TRANSPORTATION", "estimated_cost": 180},
        ],
    },
    {
        "id": "pkg-1003",
        "code": "PKG-1003",
        "name": "Cairo Heritage",
        "city": "Cairo",
        "duration": "6 days / 5 nights",
        "price": 780,
        "includes": "Hotel + Pyramids + Nile dinner",
        "status": "INACTIVE",
        "excluded": "Domestic flights",
        "services": [
            {"id": "svc-1001", "supplier_id": "sup-1001", "supplier": "Nile View Hotel", "name": "Twin BB — Nile view, 5 nights", "kind": "ACCOMMODATION", "estimated_cost": 3000},
            {"id": "svc-1002", "supplier_id": "sup-1002", "supplier": "Beirut Transport Co.", "name": "Airport arrivals and old-city coach", "kind": "TRANSPORTATION", "estimated_cost": 180},
            {"id": "svc-1003", "supplier_id": "sup-1003", "supplier": "Hassan Local Tours", "name": "Licensed old-city guide", "kind": "GUIDE", "estimated_cost": 250},
        ],
    },
]

SUPPLIERS = [
    {
        "id": "sup-1001",
        "number": "SUP-1001",
        "name": "Nile View Hotel",
        "type": "HOTEL",
        "type_label": "Hotel",
        "contact": "Sara Ali",
        "phone": "+20 2 555 0100",
        "email": "reservations@nileview.example",
        "city": "Cairo",
        "owed": 1000,
        "status": "ACTIVE",
        "terms": "Net 14",
        "bank": "Banque Misr · EG12 0001 0002",
        "stars": 4,
        "rooms": 120,
        "board": "BB",
        "checkin": "14:00",
        "checkout": "12:00",
    },
    {
        "id": "sup-1002",
        "number": "SUP-1002",
        "name": "Beirut Transport Co.",
        "type": "TRANSPORTATION",
        "type_label": "Transportation",
        "contact": "Karim Nassar",
        "phone": "+961 1 445 090",
        "email": "ops@beiruttransport.example",
        "city": "Beirut",
        "owed": 180,
        "status": "ACTIVE",
        "terms": "Net 7",
        "bank": "BLOM · LB88 003",
        "vehicle": "Coach",
        "fleet": 12,
        "seats": 48,
    },
    {
        "id": "sup-1003",
        "number": "SUP-1003",
        "name": "Hassan Local Tours",
        "type": "TOUR_GUIDE",
        "type_label": "Guide",
        "contact": "Hassan Farid",
        "phone": "+20 10 200 3344",
        "email": "hassan@localtours.example",
        "city": "Cairo",
        "owed": 250,
        "status": "ACTIVE",
        "terms": "On completion",
        "bank": "CIB · EG55 009",
        "languages": "Arabic, English, French",
        "years": 11,
        "specialties": "Pharaonic history, Islamic Cairo",
    },
    {
        "id": "sup-1004",
        "number": "SUP-1004",
        "name": "Bosphorus Hotel",
        "type": "HOTEL",
        "type_label": "Hotel",
        "contact": "Leyla Arslan",
        "phone": "+90 212 555 0101",
        "email": "groups@bosphorushotel.example",
        "city": "Istanbul",
        "owed": 9000,
        "status": "ACTIVE",
        "terms": "30% on confirmation",
        "bank": "Garanti BBVA · TR33 0006 2000",
        "stars": 4,
        "rooms": 80,
        "board": "BB",
        "checkin": "14:00",
        "checkout": "12:00",
    },
    {
        "id": "sup-1005",
        "number": "SUP-1005",
        "name": "Istanbul Transport",
        "type": "TRANSPORTATION",
        "type_label": "Transportation",
        "contact": "Ozan Kilic",
        "phone": "+90 212 555 0202",
        "email": "ops@istanbultransport.example",
        "city": "Istanbul",
        "owed": 4500,
        "status": "ACTIVE",
        "terms": "Net 7",
        "bank": "Isbank · TR64 0006 4000",
        "vehicle": "Mercedes Sprinter",
        "fleet": 10,
        "seats": 16,
    },
    {
        "id": "sup-1006",
        "number": "SUP-1006",
        "name": "Istanbul Local Guide",
        "type": "TOUR_GUIDE",
        "type_label": "Guide",
        "contact": "Defne Yilmaz",
        "phone": "+90 532 555 0303",
        "email": "defne@istanbullocalguide.example",
        "city": "Istanbul",
        "owed": 2000,
        "status": "ACTIVE",
        "terms": "Cash on completion",
        "bank": "—",
        "languages": "Turkish, English",
        "years": 12,
        "specialties": "Old city, Bosphorus, food",
    },
]

SERVICES = [
    {
        "id": "svc-1001",
        "number": "SVC-1001",
        "supplier_id": "sup-1001",
        "supplier": "Nile View Hotel",
        "name": "Twin BB — Nile view, 5 nights",
        "kind": "ACCOMMODATION",
        "kind_label": "Accommodation",
        "estimated_cost": 3000,
        "cost_basis": "PER_GROUP",
        "status": "ACTIVE",
    },
    {
        "id": "svc-1002",
        "number": "SVC-1002",
        "supplier_id": "sup-1002",
        "supplier": "Beirut Transport Co.",
        "name": "Airport arrivals and old-city coach",
        "kind": "TRANSPORTATION",
        "kind_label": "Transportation",
        "estimated_cost": 180,
        "cost_basis": "PER_GROUP",
        "status": "ACTIVE",
    },
    {
        "id": "svc-1003",
        "number": "SVC-1003",
        "supplier_id": "sup-1003",
        "supplier": "Hassan Local Tours",
        "name": "Licensed old-city guide",
        "kind": "GUIDE",
        "kind_label": "Guided tour",
        "estimated_cost": 250,
        "cost_basis": "PER_GROUP",
        "status": "ACTIVE",
    },
    {
        "id": "svc-1004",
        "number": "SVC-1004",
        "supplier_id": "sup-1004",
        "supplier": "Bosphorus Hotel",
        "name": "Accommodation",
        "kind": "ACCOMMODATION",
        "kind_label": "Accommodation",
        "estimated_cost": 9000,
        "cost_basis": "PER_GROUP",
        "status": "ACTIVE",
    },
    {
        "id": "svc-1005",
        "number": "SVC-1005",
        "supplier_id": "sup-1005",
        "supplier": "Istanbul Transport",
        "name": "Airport Transfer",
        "kind": "TRANSPORTATION",
        "kind_label": "Transportation",
        "estimated_cost": 1500,
        "cost_basis": "PER_GROUP",
        "status": "ACTIVE",
    },
    {
        "id": "svc-1006",
        "number": "SVC-1006",
        "supplier_id": "sup-1005",
        "supplier": "Istanbul Transport",
        "name": "Full-Day Transportation",
        "kind": "TRANSPORTATION",
        "kind_label": "Transportation",
        "estimated_cost": 3000,
        "cost_basis": "PER_GROUP",
        "status": "ACTIVE",
    },
    {
        "id": "svc-1007",
        "number": "SVC-1007",
        "supplier_id": "sup-1006",
        "supplier": "Istanbul Local Guide",
        "name": "City Tour",
        "kind": "GUIDE",
        "kind_label": "Guided tour",
        "estimated_cost": 2000,
        "cost_basis": "PER_GROUP",
        "status": "ACTIVE",
    },
]

BOOKINGS = [
    {
        "id": "bk-1048",
        "number": "BK-1048",
        "customer": "Fatima Ghazzawi",
        "customer_id": "cus-1001",
        "product": "Cairo Discovery",
        "package": "Cairo Heritage",
        "tour_id": "tour-1001",
        "kind": "TOUR",
        "dates": "12–16 Sep 2026",
        "travelers": 4,
        "status": "CONFIRMED",
        "pay": "PARTIALLY_PAID",
        "total": 2400,
        "paid": 1980,
        "remaining": 420,
        "destination": "Cairo",
    },
    {
        "id": "bk-1088",
        "number": "BK-1088",
        "customer": "Sarah Ahmad",
        "customer_id": "cus-1002",
        "product": "Istanbul Explorer",
        "package": "Istanbul Essentials",
        "tour_id": "tour-1002",
        "kind": "TOUR",
        "dates": "15–20 Sep 2026",
        "travelers": 2,
        "status": "CONFIRMED",
        "pay": "PAID",
        "total": 1780,
        "paid": 1780,
        "remaining": 0,
        "destination": "Istanbul",
    },
    {
        "id": "bk-1090",
        "number": "BK-1090",
        "customer": "Omar Khalil",
        "customer_id": "cus-1003",
        "product": "Dubai Escape — Sep",
        "package": "Dubai Escape",
        "tour_id": "tour-1004",
        "kind": "TOUR",
        "dates": "22–26 Sep 2026",
        "travelers": 2,
        "status": "PENDING",
        "pay": "UNPAID",
        "total": 1698,
        "paid": 0,
        "remaining": 1698,
        "destination": "Dubai",
    },
    {
        "id": "bk-1071",
        "number": "BK-1071",
        "customer": "Ali Mansour",
        "customer_id": "cus-1004",
        "product": "Istanbul Essentials — Late Sep",
        "package": "Istanbul Essentials",
        "tour_id": "tour-1003",
        "kind": "TOUR",
        "dates": "20–25 Sep 2026",
        "travelers": 1,
        "status": "CANCELLED",
        "pay": "REFUNDED",
        "total": 699,
        "paid": 0,
        "remaining": 0,
        "destination": "Istanbul",
    },
]

INVOICES = [
    {
        "id": "inv-1042",
        "number": "INV-1042",
        "customer": "Fatima Ghazzawi",
        "customer_id": "cus-1001",
        "booking": "BK-1048",
        "booking_id": "bk-1048",
        "issue": "01 Aug 2026",
        "due": "15 Aug 2026",
        "total": 2400,
        "paid": 1980,
        "remaining": 420,
        "status": "PARTIALLY_PAID",
        "overdue": True,
    },
    {
        "id": "inv-1008",
        "number": "INV-1008",
        "customer": "Sarah Ahmad",
        "customer_id": "cus-1002",
        "booking": "BK-1088",
        "booking_id": "bk-1088",
        "issue": "20 Jul 2026",
        "due": "03 Aug 2026",
        "total": 1780,
        "paid": 1780,
        "remaining": 0,
        "status": "PAID",
        "overdue": False,
    },
    {
        "id": "inv-1055",
        "number": "INV-1055",
        "customer": "Omar Khalil",
        "customer_id": "cus-1003",
        "booking": "BK-1090",
        "booking_id": "bk-1090",
        "issue": "22 Aug 2026",
        "due": "05 Sep 2026",
        "total": 1698,
        "paid": 0,
        "remaining": 1698,
        "status": "ISSUED",
        "overdue": False,
    },
]

PAYMENTS = [
    {
        "id": "pay-1042",
        "number": "PAY-1042",
        "invoice": "INV-1042",
        "invoice_id": "inv-1042",
        "customer": "Fatima Ghazzawi",
        "date": "04 Aug 2026",
        "amount": 750,
        "method": "BANK_TRANSFER",
        "ref": "TRX-88921",
        "status": "COMPLETED",
        "by": "Sarah Ahmad",
    },
    {
        "id": "pay-1030",
        "number": "PAY-1030",
        "invoice": "INV-1042",
        "invoice_id": "inv-1042",
        "customer": "Fatima Ghazzawi",
        "date": "12 Aug 2026",
        "amount": 1230,
        "method": "CARD",
        "ref": "VISA-4421",
        "status": "COMPLETED",
        "by": "Sarah Ahmad",
    },
    {
        "id": "pay-1008",
        "number": "PAY-1008",
        "invoice": "INV-1008",
        "invoice_id": "inv-1008",
        "customer": "Sarah Ahmad",
        "date": "21 Jul 2026",
        "amount": 1780,
        "method": "CASH",
        "ref": "—",
        "status": "COMPLETED",
        "by": "Ali Mansour",
    },
]

RECEIPTS = [
    {
        "id": "rec-1042",
        "number": "REC-1042",
        "payment": "PAY-1042",
        "invoice": "INV-1042",
        "customer": "Fatima Ghazzawi",
        "amount": 750,
        "method": "Bank transfer",
        "issued": "04 Aug 2026 · 14:22",
        "by": "Sarah Ahmad",
    },
    {
        "id": "rec-1008",
        "number": "REC-1008",
        "payment": "PAY-1008",
        "invoice": "INV-1008",
        "customer": "Sarah Ahmad",
        "amount": 1780,
        "method": "Cash",
        "issued": "21 Jul 2026 · 11:05",
        "by": "Ali Mansour",
    },
]

REFUNDS = [
    {
        "id": "ref-1012",
        "number": "REF-1012",
        "customer": "Ali Mansour",
        "payment": "PAY-0990",
        "amount": 300,
        "original": 800,
        "already": 0,
        "refundable": 500,
        "reason": "Traveler dropped; remaining party continues.",
        "status": "PENDING",
        "requested": "26 Aug 2026",
        "approver": "—",
        "booking": "BK-1071",
    },
    {
        "id": "ref-1004",
        "number": "REF-1004",
        "customer": "Omar Khalil",
        "payment": "PAY-0981",
        "amount": 200,
        "original": 900,
        "already": 0,
        "refundable": 700,
        "reason": "Room category downgrade.",
        "status": "APPROVED",
        "requested": "18 Aug 2026",
        "approver": "Amina Hassan",
        "booking": "BK-1060",
    },
    {
        "id": "ref-1001",
        "number": "REF-1001",
        "customer": "Sarah Ahmad",
        "payment": "PAY-0902",
        "amount": 150,
        "original": 1500,
        "already": 150,
        "refundable": 0,
        "reason": "Activity cancelled by supplier.",
        "status": "COMPLETED",
        "requested": "02 Aug 2026",
        "approver": "Amina Hassan",
        "booking": "BK-1055",
    },
]

EXPENSES = [
    {
        "id": "exp-1041",
        "number": "EXP-1041",
        "supplier": "Nile View Hotel",
        "supplier_id": "sup-1001",
        "related": "Cairo Discovery",
        "category": "HOTEL",
        "amount": 3000,
        "paid": 2000,
        "remaining": 1000,
        "due": "10 Sep 2026",
        "status": "PARTIALLY_PAID",
        "overdue": False,
        "scope": "TOUR",
    },
    {
        "id": "exp-1033",
        "number": "EXP-1033",
        "supplier": "Beirut Transport Co.",
        "supplier_id": "sup-1002",
        "related": "Cairo Discovery",
        "category": "TRANSPORTATION",
        "amount": 180,
        "paid": 0,
        "remaining": 180,
        "due": "08 Sep 2026",
        "status": "UNPAID",
        "overdue": True,
        "scope": "TOUR",
    },
    {
        "id": "exp-1028",
        "number": "EXP-1028",
        "supplier": "Hassan Local Tours",
        "supplier_id": "sup-1003",
        "related": "Cairo Discovery",
        "category": "TOUR_GUIDE",
        "amount": 250,
        "paid": 0,
        "remaining": 250,
        "due": "12 Sep 2026",
        "status": "UNPAID",
        "overdue": False,
        "scope": "TOUR",
    },
    {
        "id": "exp-1010",
        "number": "EXP-1010",
        "supplier": "—",
        "supplier_id": None,
        "related": "General",
        "category": "RENT",
        "amount": 1400,
        "paid": 1400,
        "remaining": 0,
        "due": "01 Aug 2026",
        "status": "PAID",
        "overdue": False,
        "scope": "GENERAL",
    },
]

SUPPLIER_PAYMENTS = [
    {
        "id": "sp-1008",
        "number": "SP-1008",
        "supplier": "Nile View Hotel",
        "expense": "EXP-1041",
        "expense_id": "exp-1041",
        "amount": 2000,
        "method": "BANK_TRANSFER",
        "date": "20 Aug 2026",
        "ref": "AP-4410",
    }
]

USERS = [
    {
        "id": "usr-1",
        "name": "Amina Hassan",
        "initials": "AH",
        "email": "owner@tourops.local",
        "role": "OWNER_ADMIN",
        "role_label": "Owner / Admin",
        "status": "ACTIVE",
        "last": "Today, 07:14",
    },
    {
        "id": "usr-2",
        "name": "Sarah Ahmad",
        "initials": "SA",
        "email": "sarah@tourops.local",
        "role": "ACCOUNTANT",
        "role_label": "Accountant",
        "status": "ACTIVE",
        "last": "Yesterday, 18:02",
    },
    {
        "id": "usr-3",
        "name": "Ali Mansour",
        "initials": "AM",
        "email": "ali@tourops.local",
        "role": "TRAVEL_AGENT",
        "role_label": "Travel Agent",
        "status": "ACTIVE",
        "last": "Today, 09:41",
    },
    {
        "id": "usr-4",
        "name": "Lina Farhat",
        "initials": "LF",
        "email": "lina@tourops.local",
        "role": "TRAVEL_AGENT",
        "role_label": "Travel Agent",
        "status": "INACTIVE",
        "last": "12 Jun 2026",
    },
]

ACTIVITY = [
    {"time": "09:42 AM", "who": "Sarah Ahmad", "text": "Recorded a $750 payment for INV-1042", "kind": "payment"},
    {"time": "09:18 AM", "who": "Ali Mansour", "text": "Confirmed booking BK-1088", "kind": "booking"},
    {"time": "Yesterday", "who": "Amina Hassan", "text": "Refund REF-1012 is awaiting approval", "kind": "refund"},
    {"time": "Yesterday", "who": "Ali Mansour", "text": "Added 4 travelers to BK-1048", "kind": "booking"},
    {"time": "Mon", "who": "Sarah Ahmad", "text": "Recorded supplier payment SP-1008 · $2,000", "kind": "supplier"},
]

NOTIFICATIONS = [
    {"when": "Today", "title": "Refund awaiting approval", "body": "REF-1012 · Ali Mansour · $300", "kind": "refund", "unread": True},
    {"when": "Today", "title": "Invoice overdue", "body": "INV-1042 · Fatima Ghazzawi · $420 remaining", "kind": "payment", "unread": True},
    {"when": "Yesterday", "title": "Tour near capacity", "body": "Cairo Discovery is 18/25 seats (72%)", "kind": "tour", "unread": True},
    {"when": "Yesterday", "title": "Supplier payment due", "body": "Beirut Transport Co. · EXP-1033 · $180", "kind": "supplier", "unread": False},
    {"when": "Earlier", "title": "Booking confirmed", "body": "BK-1088 Istanbul Explorer is confirmed and paid", "kind": "booking", "unread": False},
]

ITINERARY = [
    {"day": "Day 1 · 12 Sep", "title": "Airport transfer", "supplier": "Beirut Transport Co.", "est": 180},
    {"day": "Day 1 · 12 Sep", "title": "Hotel — Nile View", "supplier": "Nile View Hotel", "est": 1200},
    {"day": "Day 2 · 13 Sep", "title": "Local guide", "supplier": "Hassan Local Tours", "est": 250},
    {"day": "Day 3 · 14 Sep", "title": "Pyramids day coach", "supplier": "Beirut Transport Co.", "est": 220},
]

TRAVELERS = [
    {"name": "Fatima Ghazzawi", "passport": "LR445821", "dob": "12 Mar 1992", "type": "Adult"},
    {"name": "Rami Ghazzawi", "passport": "LR445822", "dob": "04 Sep 1989", "type": "Adult"},
    {"name": "Nour Ghazzawi", "passport": "LR551002", "dob": "21 Jan 2016", "type": "Child"},
    {"name": "Lina Ghazzawi", "passport": "LR551003", "dob": "08 Jul 2018", "type": "Child"},
]

AUDIT = [
    {"time": "09:42 AM", "date": "29 Aug 2026", "who": "Sarah Ahmad", "action": "Recorded payment", "entity": "PAY-1042", "related": "Invoice INV-1008", "amount": 500, "kind": "payment"},
    {"time": "09:18 AM", "date": "29 Aug 2026", "who": "Ali Mansour", "action": "Confirmed booking", "entity": "BK-1088", "related": "Istanbul Explorer", "amount": None, "kind": "booking"},
    {"time": "18:02 PM", "date": "28 Aug 2026", "who": "Amina Hassan", "action": "Opened refund review", "entity": "REF-1012", "related": "Ali Mansour", "amount": 300, "kind": "refund"},
    {"time": "11:40 AM", "date": "28 Aug 2026", "who": "Ali Mansour", "action": "Added travelers", "entity": "BK-1048", "related": "Cairo Discovery", "amount": None, "kind": "booking"},
    {"time": "16:10 PM", "date": "27 Aug 2026", "who": "Sarah Ahmad", "action": "Recorded supplier payment", "entity": "SP-1008", "related": "Nile View Hotel", "amount": 2000, "kind": "supplier"},
    {"time": "10:05 AM", "date": "26 Aug 2026", "who": "Amina Hassan", "action": "Issued invoice", "entity": "INV-1055", "related": "Omar Khalil", "amount": 1698, "kind": "invoice"},
]

CUSTOMER_TIMELINE = [
    {"date": "12 Aug", "label": "Payment PAY-1030", "amount": 1230, "sign": "+"},
    {"date": "04 Aug", "label": "Payment PAY-1042", "amount": 750, "sign": "+"},
    {"date": "01 Aug", "label": "Invoice INV-1042 issued", "amount": 2400, "sign": "inv"},
    {"date": "18 Jul", "label": "Booking BK-1048 confirmed", "amount": None, "sign": "bk"},
]

ATTENTION = [
    {"count": 5, "label": "overdue invoices", "hint": "Oldest: INV-1042 · Fatima Ghazzawi", "href_name": "invoices:list"},
    {"count": 3, "label": "refunds awaiting approval", "hint": "REF-1012 needs a decision today", "href_name": "refunds:list"},
    {"count": 2, "label": "tours near capacity", "hint": "Cairo Discovery 18/25 · Istanbul full", "href_name": "tours:list"},
    {"count": 4, "label": "supplier payments due this week", "hint": "Beirut Transport Co. · $180 overdue", "href_name": "supplier_payments:list"},
]

SETTINGS = {
    "agency": "TourOps Travel",
    "legal": "TourOps Agency SARL",
    "phone": "+961 1 555 220",
    "email": "hello@tourops.example",
    "address": "Hamra Street, Beirut, Lebanon",
    "currency": "USD",
    "tax_name": "VAT",
    "tax_rate": 11,
    "prefixes": [
        ("Customer", "CUS"),
        ("Booking", "BK"),
        ("Invoice", "INV"),
        ("Payment", "PAY"),
        ("Receipt", "REC"),
        ("Refund", "REF"),
        ("Expense", "EXP"),
        ("Supplier payment", "SP"),
        ("Tour", "TOUR"),
        ("Package", "PKG"),
    ],
}


def get(kind: str, ident: str) -> dict:
    tables = {
        "customer": (CUSTOMERS, "id"),
        "tour": (TOURS, "id"),
        "package": (PACKAGES, "id"),
        "supplier": (SUPPLIERS, "id"),
        "service": (SERVICES, "id"),
        "booking": (BOOKINGS, "number"),
        "invoice": (INVOICES, "id"),
        "payment": (PAYMENTS, "id"),
        "receipt": (RECEIPTS, "id"),
        "refund": (REFUNDS, "id"),
        "expense": (EXPENSES, "id"),
        "sp": (SUPPLIER_PAYMENTS, "id"),
        "user": (USERS, "id"),
    }
    rows, key = tables[kind]
    return _by_id(rows, key, ident)


MOCK = {
    "customers": CUSTOMERS,
    "tours": TOURS,
    "packages": PACKAGES,
    "suppliers": SUPPLIERS,
    "services": SERVICES,
    "bookings": BOOKINGS,
    "invoices": INVOICES,
    "payments": PAYMENTS,
    "receipts": RECEIPTS,
    "refunds": REFUNDS,
    "expenses": EXPENSES,
    "supplier_payments": SUPPLIER_PAYMENTS,
    "users": USERS,
    "activity": ACTIVITY,
    "notifications": NOTIFICATIONS,
    "itinerary": ITINERARY,
    "travelers": TRAVELERS,
    "audit": AUDIT,
    "customer_timeline": CUSTOMER_TIMELINE,
    "attention": ATTENTION,
    "settings": SETTINGS,
    "kpis": {
        "revenue": 49640,
        "revenue_delta": 12.4,
        "ar": 2118,
        "ar_delta": -6.1,
        "ap": 1430,
        "ap_delta": 3.2,
        "active_bookings": 18,
        "upcoming": 4,
        "profit": 14340,
        "profit_delta": 8.7,
    },
    "pipeline": {"pending": 3, "confirmed": 11, "progress": 2, "completed": 24},
    "money_in": 18420,
    "money_out": 6120,
    "unread": 3,
}
